# Generated by Django 5.2.12 on 2026-03-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=64, unique=True)),
                ('instance_name', models.CharField(max_length=255)),
                ('friendly_name', models.CharField(blank=True, default='', max_length=255)),
                ('module', models.CharField(blank=True, default='', max_length=128)),
                ('running', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['instance_name'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.IntegerField()),
                ('protocol_name', models.CharField(default='', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('required', models.BooleanField(blank=True, null=True)),
                ('listening', models.BooleanField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('is_user_defined', models.BooleanField(blank=True, null=True)),
                ('is_firewall_target', models.BooleanField(blank=True, null=True)),
                ('range', models.IntegerField(blank=True, null=True)),
                ('network_raw', models.JSONField(blank=True, null=True)),
                ('core_raw', models.JSONField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ports.discoveredinstance')),
            ],
            options={
                'ordering': ['port', 'protocol'],
                'constraints': [models.UniqueConstraint(fields=('instance', 'port', 'protocol'), name='uniq_discovered_port_per_instance')],
            },
        ),
    ]
