# Generated by Codex on 2026-03-09

from __future__ import annotations

import json

from django.db import migrations, models


def _as_bool(value: object, default: bool) -> bool:
    if value is None:
        return default
    text = str(value).strip().lower()
    if text in {"1", "true", "yes", "on"}:
        return True
    if text in {"0", "false", "no", "off"}:
        return False
    return default


def migrate_json_config_to_fields(apps, schema_editor):
    from ports.security import encrypt_secret

    FirewallProviderConfig = apps.get_model("ports", "FirewallProviderConfig")
    for row in FirewallProviderConfig.objects.all():
        cfg = row.config or {}
        if not isinstance(cfg, dict):
            cfg = {}
        if row.provider_id != "openwrt":
            continue

        auth = cfg.get("auth", {})
        if isinstance(auth, str):
            try:
                parsed = json.loads(auth)
                auth = parsed if isinstance(parsed, dict) else {}
            except json.JSONDecodeError:
                auth = {}
        if not isinstance(auth, dict):
            auth = {}

        row.openwrt_rpc_url = str(cfg.get("rpc_url", row.openwrt_rpc_url or "")).strip()
        row.openwrt_username = str(auth.get("username", row.openwrt_username or "")).strip()
        password = str(auth.get("password", "")).strip()
        if password:
            row.openwrt_password_encrypted = encrypt_secret(password)
        row.openwrt_source_zone = str(cfg.get("source_zone", row.openwrt_source_zone or "publicinternal")).strip()
        row.openwrt_forward_source_zone = str(
            cfg.get("forward_source_zone", row.openwrt_forward_source_zone or "wan")
        ).strip()
        row.openwrt_forward_dest_zone = str(
            cfg.get("forward_dest_zone", row.openwrt_forward_dest_zone or "publicinternal")
        ).strip()
        row.openwrt_forward_dest_ip = str(cfg.get("forward_dest_ip", row.openwrt_forward_dest_ip or "")).strip()
        row.openwrt_manage_mode = str(cfg.get("manage_mode", row.openwrt_manage_mode or "redirect")).strip()
        row.openwrt_aggressive_mode = _as_bool(cfg.get("aggressive_mode"), row.openwrt_aggressive_mode)
        row.openwrt_name_prefix = str(cfg.get("name_prefix", row.openwrt_name_prefix or "arksa-ports-web")).strip()
        row.openwrt_display_prefix = str(cfg.get("display_prefix", row.openwrt_display_prefix or "AMP:")).strip()
        row.save(
            update_fields=[
                "openwrt_rpc_url",
                "openwrt_username",
                "openwrt_password_encrypted",
                "openwrt_source_zone",
                "openwrt_forward_source_zone",
                "openwrt_forward_dest_zone",
                "openwrt_forward_dest_ip",
                "openwrt_manage_mode",
                "openwrt_aggressive_mode",
                "openwrt_name_prefix",
                "openwrt_display_prefix",
                "updated_at",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("ports", "0002_firewallproviderconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_aggressive_mode",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_display_prefix",
            field=models.CharField(blank=True, default="AMP:", max_length=64),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_forward_dest_ip",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_forward_dest_zone",
            field=models.CharField(blank=True, default="publicinternal", max_length=64),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_forward_source_zone",
            field=models.CharField(blank=True, default="wan", max_length=64),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_manage_mode",
            field=models.CharField(blank=True, default="redirect", max_length=32),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_name_prefix",
            field=models.CharField(blank=True, default="arksa-ports-web", max_length=128),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_password_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_rpc_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_source_zone",
            field=models.CharField(blank=True, default="publicinternal", max_length=64),
        ),
        migrations.AddField(
            model_name="firewallproviderconfig",
            name="openwrt_username",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.RunPython(migrate_json_config_to_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="firewallproviderconfig",
            name="config",
        ),
    ]
