# Generated by Codex on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ports", "0003_provider_config_fields_and_encrypted_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="AMPConnectionConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_key", models.CharField(default="default", max_length=32, unique=True)),
                ("url", models.CharField(blank=True, default="", max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=128)),
                ("password_encrypted", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["config_key"],
            },
        ),
    ]
